function command = deface_scans(sub,SUBBIDS)

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Defacing anatomical scans for %s' ...
    '\n\n' ...
    '# Loading required modules\n' ...
    'module load python\n' ...
    'module load FSL' ...
    '\n\n' ...
    '# Changing working dir\n' ...
    'cd %s/anat' ...
    '\n\n' ...
    'scan=$(ls ./*T1map.nii)\n' ...
    'echo "Defacing T1map..."\n' ...
    'pydeface $scan' ...
    '\n\n' ...
    'scan=$(ls ./*UNIT1.nii)\n' ...
    'echo "Defacing UNIT1..."\n' ...
    'pydeface $scan' ...
    '\n\n' ...
    'scan=$(ls ./*INV1.nii)\n' ...
    'echo "Defacing INV1..."\n' ...
    'pydeface $scan' ...
    '\n\n' ...
    'scan=$(ls ./*INV2.nii)\n' ...
    'echo "Defacing INV2..."\n' ...
    'pydeface $scan'], ...
    sub,SUBBIDS);



end