function command = realign_runs(runs,tag,target_ind,FUNCDIR)

target_run = sprintf('%s/%s_%s',FUNCDIR,tag,runs(target_ind));
runs(target_ind) = [];

command = sprintf(['#~/bin/bash' ...
    '\n\n' ...
    '# Load required module\n' ...
    'module load FSL' ...
    '\n\n' ...
    '# realigns runs\n' ...
    'REF=%s' ...
    '\n\n'], ...
    target_run);

for i = 1:length(runs)

    run = sprintf('%s/%s_%s',FUNCDIR,tag,runs(i));

    command = sprintf(['%s' ...
        'echo "Realigning run %d"\n' ...
    'fslcpgeom "$REF" %s' ...
    '\n\n'], ...
    command,i,run);

end

end