function command = upsample_images(images,outnames,factors,OUTDIR)

factors = 1 ./ factors; % upsampling factor of the images

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Loading required module\n' ...
    'module load AFNI' ...
    '\n\n' ...
    '# Changing to output directory\n' ...
    'cd %s' ...
    '\n\n'], ...
    OUTDIR);

for i = 1:length(images)

    command = sprintf(['%s' ...
        'echo "Upsampling image %d: %s"\n' ...
        '3dresample -input %s -prefix %s -dxyz %f %f %f -overwrite' ...
        '\n\n'], ...
        command,i,images(i),images(i),outnames(i),factors(1),factors(2),factors(3));

end

end