function command = bold_correction(bold_runs,vaso_runs,OUTDIR)

% OUTDIR also contains all the relevant runs

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Correcting BOLD contamination' ...
    '\n\n' ...
    '# loading required module\n' ...
    'module load AFNI' ...
    '\n\n' ...
    '# moving to working dir\n' ...
    'cd %s' ...
    '\n\n'], ...
    OUTDIR);

% one correction occurs per run
for i = 1:length(bold_runs)

    bold = bold_runs(i) ; vaso = vaso_runs(i);

    command = sprintf(['%s' ...
        'echo "Correcting run %d"' ...
        '\n\n' ...
        'echo "BOLD correction..."\n' ...
        'LN_BOCO -Nulled r_%s -BOLD r_%s' ...
        '\n\n' ...
        'echo "Renaming files..."\n' ...
        'mv -v VASO_LN.nii br_%s' ...
        '\n\n' ...
        'echo "Correcting mean file %d"' ...
        '\n\n' ...
        'echo "BOLD correction..."\n' ...
        'LN_BOCO -Nulled mean%s -BOLD mean%s' ...
        '\n\n' ...
        'echo "Renaming files..."\n' ...
        'mv -v VASO_LN.nii bmean%s' ...
        '\n\n'], ...
        command,i,vaso,bold,vaso,i,vaso,bold,vaso);

end