function command = bold_correction(bold_runs,vaso_runs,OUTDIR,PREFIX)

% OUTDIR also contains all the relevant runs

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Correcting BOLD contamination' ...
    '\n\n' ...
    '# loading required module\n' ...
    'module load AFNI' ...
    '\n\n' ...
    '# moving to working dir\n' ...
    'cd %s' ...
    '\n\n'], ...
    OUTDIR);

% one correction occurs per run
for i = 1:length(bold_runs)

    bold = bold_runs(i) ; vaso = vaso_runs(i);

    command = sprintf(['%s' ...
        'echo "Correcting image %d"' ...
        '\n\n' ...
        'echo "BOLD correction..."\n' ...
        'LN_BOCO -Nulled %s -BOLD %s' ...
        '\n\n' ...
        'echo "Renaming files..."\n' ...
        'mv -v VASO_LN.nii %s%s' ...
        '\n\n'], ...
        command,i,vaso,bold,PREFIX,vaso,i,vaso,bold,PREFIX,vaso);

end