function command = convert_dicom(sub,DICOM,CODEDIR,BIDS)

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Converting dicom to nifti for %s' ...
    '\n\n' ...
    'module load dcm2niix\n' ...
    'module load dcm2bids\n' ...
    '\n' ...
    'dcm2bids -d %s -p %s -c %s/bids-config.json -o %s'], ...
    sub,DICOM,sub,CODEDIR,BIDS);
