function command = deface_scans(anat_files,OUTDIR)

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Defacing anatomical scans' ...
    '\n\n' ...
    '# Loading required modules\n' ...
    'module load python\n' ...
    'module load FSL' ...
    '\n\n' ...
    '# Changing working dir\n' ...
    'cd %s/anat' ...
    '\n\n'], ...
    OUTDIR);

for i = 1:length(anat_files)

    command = sprintf(['%s' ...
        'echo "Defacing %s..."\n' ...
        'scan=$(ls ./*%s.nii)\n' ...
        'pydeface $scan' ...
        '\n\n'], ...
        command,anat_files{i},anat_files{i});

end

end