function command = generate_t1_like(bold,vaso,outname,OUTDIR)

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Loading required module\n' ...
    'module load AFNI' ...
    '\n\n' ...
    '# Changing to anat directory\n' ...
    'cd %s' ...
    '\n\n' ...
    'echo "Generating T1-like image..."\n' ...
    '3dcalc -a %s -b %s -expr "(a+b)/(a-b)" -datum float -prefix %s -overwrite'], ...
    OUTDIR,bold,vaso,outname);

end