function command = grow_layers(masks,num_layers,MASKDIR)

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    'cd %s' ...
    '\n\n'], ...
    MASKDIR);

for i = 1:length(masks)

    command = sprintf(['%s' ...
        '# Growing layers for mask %d\n' ...
        'LN_GROW_LAYERS -rim %s -N %d' ...
        '\n\n'], ...
        command,i,masks(i),num_layers);
end

end