function command = profile_layers(rois,funcmaps,OUTDIR)

command = sprintf(['#!/bin/bash' ...
    '\n\n' ...
    '# Profiling layer activation' ...
    '\n\n' ...
    '# moving to working dir\n' ...
    'cd %s' ...
    '\n\n'], ...
    OUTDIR);

for c = 1:length(funcmaps)
    for r = 1:length(rois)
        command = sprintf(['%s' ...
            'echo "Profiling contrast %d for roi %s"\n' ...
            'LN2_PROFILE -input %s -layers %s-mask_layers_equidist.nii -plot -output %s-profile-c%d.txt' ...
            '\n\n'], ...
            command,c,rois(r),funcmaps(c),rois(r),rois(r),c);
    end
end


end